### PR TITLE
Made the vagrant machine independent of docker

### PR DESCRIPTION
**Pull request by nwehr**
I've upgraded the vagrant machine to Ubuntu 15.10 with all the requisite guest additions for virtual box. The two provisioning scripts install all the dependencies and setup the environment.

### CODE REVIEW

**Comment by danil** [comment]
@nwehr Thanks! But keep in mind Fhirbase version 1 is deprecated.
You can use Fhirbase version 2 (yet in the beta)
<https://github.com/fhirbase/fhirbase-plv8>

**Comment by nwehr** [comment]
@danil Ok good to know. What's the brief difference in v2?

**Comment by danil** [comment]
@nwehr Fhirbase 2 switched from PLpgSQL to plv8 (V8 Engine Javascript Procedural Language add-on for PostgreSQL)

**Comment by danil** [comment]
@nwehr also Fhirbase version 2 supports FHIR version DSTU2

**Pull request merged**
