### PR TITLE
Preserving the 'id' attribute in resource upon persistence.

### PR DESCRIPTION
**Pull request by daya**
This change will bring consistency with `fhirbase load` functionality which preserves the `id` attribute in resource

### CODE REVIEW

**Comment by daya** [comment]
This refers to issue #19

**Comment by daya** [comment]
This is apparently failing for reasons not related to the change

`Failed to create GitHub release page: failed to get release: get release tag: invalid status: 401 Unauthorized: GET https://api.github.com/repos/fhirbase/fhirbase/releases/tags/nightly-build: 401 Bad credentials`

**Comment by daya** [comment]
@mlapshin @niquola any ideas on how to proceed from here?

**Review by mlapshin — APPROVED** [review]

**Comment by mlapshin** [comment]
@daya Thanks for your contribution and sorry for long approval.

**Pull request merged**
